name: flutter_image
version: 2.0.0-dev
description: >
  Image utilities for Flutter: providers, effects, etc
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/flutter_image

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  quiver: '>=0.24.0 <2.0.0'
  test: any
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.9 <2.0.0"
