name: cupertino_ui
description: The Flutter Cupertino Design Library
version: 0.0.1
repository: https://github.com/flutter/packages/tree/main/packages/cupertino_ui
issue_tracker: https://github.com/flutter/flutter/issues?q=state%3Aopen%20label%3A%22f%3A%20cupertino%22

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - ui
  - widgets
  - cupertino
  - ios
