name: local_auth_darwin
description: iOS implementation of the local_auth plugin.
repository: https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth_darwin
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+local_auth%22
version: 1.4.3

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

flutter:
  plugin:
    implements: local_auth
    platforms:
      ios:
        pluginClass: FLALocalAuthPlugin
        dartPluginClass: LocalAuthDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: FLALocalAuthPlugin
        dartPluginClass: LocalAuthDarwin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <0.21.0"
  local_auth_platform_interface: ^1.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^22.4.0

topics:
  - authentication
  - biometrics
  - local-auth
