# The list of external dependencies that are allowed as pinned dependencies.
# See https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#Dependencies
#
# All entries here should have an explanation for why they are here.

# TODO(stuartmorgan): Eliminate this in favor of standardizing on
# mockito. See https://github.com/flutter/flutter/issues/130757
- mocktail

# Test-only dependency, so does not impact package clients, and
# has limited impact so could be easily removed if there are
# ever maintenance issues in the future.
- lcov_parser

# This should be removed; see
# https://github.com/flutter/flutter/issues/130897
- provider

## Allowed by default

# Dart-owned
- dart_style
- mockito

# Google-owned
- file_testing
