# This list should be kept as short as possible, and things should remain here
# only as long as necessary, since in general the goal is for all of the latest
# versions of packages to be mutually compatible.
#
# An example use case for this list would be to temporarily add packages while
# updating multiple packages for a breaking change in a common dependency in
# cases where using a relaxed version constraint isn't possible.

# This is a permament entry, as it should never be a direct app dependency.
- plugin_platform_interface
