# This list should be kept as short as possible, and things should remain here
# only as long as necessary, since in general the goal is for all of the latest
# versions of packages to be mutually compatible.
#
# An example use case for this list would be to temporarily add packages while
# updating multiple packages for a breaking change in a common dependency in
# cases where using a relaxed version constraint isn't possible.

# NOTE: camera_android is semi-excluded via special casing in the repo tools.
# See create_all_packages_app_command.dart.

# This is a permanent entry, as it should never be a direct app dependency.
- plugin_platform_interface
# Temporarily excluded since it hasn't been updated for the major version
# change in google_sign_in. https://github.com/flutter/flutter/issues/171048
- extension_google_sign_in_as_googleapis_auth
