# Packages that are excluded from dart unit test on Windows.
# Exclude flutter_image because its tests need a test server, so are run via custom_package_tests.
- flutter_image
# This test is very slow, so isn't worth running a second time
# on Windows; the Linux run is enough coverage.
- flutter_migrate
# TODO(stuartmorgan): Fix these tests to run correctly on a
# Windows host and enable them.
- path_provider_linux
- webview_flutter_android
# Unit tests for plugins that support web currently run in
# Chrome, which isn't currently supported by web infrastructure.
# TODO(ditman): Fix this in the repo tooling.
- camera
- camera_web
- file_selector
- file_selector_web
- google_maps_flutter_web
- google_sign_in
- google_sign_in_web
- image_picker
- image_picker_for_web
- shared_preferences
- shared_preferences_web
- url_launcher
- url_launcher_web
- video_player
- video_player_web
- webview_flutter_web
