name: quick_actions_ios
description: An implementation for the iOS platform of the Flutter `quick_actions` plugin.
repository: https://github.com/flutter/packages/tree/main/packages/quick_actions/quick_actions_ios
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+in_app_purchase%22
version: 1.2.0

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: quick_actions
    platforms:
      ios:
        pluginClass: QuickActionsPlugin
        dartPluginClass: QuickActionsIos

dependencies:
  flutter:
    sdk: flutter
  quick_actions_platform_interface: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^20.0.1
  plugin_platform_interface: ^2.1.7

topics:
  - quick-actions
  - os-integration
