name: go_router_examples
description: go_router examples
version: 3.0.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  adaptive_navigation: ^0.0.4
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router:
    path: ..
  logging: ^1.0.0
  provider: 6.0.5
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
