name: video_player_windows
description: Windows implementation of the video_player plugin.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player_windows
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.5.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      windows:
        dartPluginClass: WindowsVideoPlayer
        pluginClass: VideoPlayerWindows

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ">=6.1.0 <7.0.0"

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  pigeon: ^16.0.3

topics:
  - video
  - video-player
