name: cross_file_web_example
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  file_selector:
    path: ../../../file_selector/file_selector
  flutter:
    sdk: flutter
  mime: ^2.0.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
