name: cross_file_web_example
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  file_selector:
    git:
      url: https://github.com/bparrishMines/packages
      ref: new_file_selector
      path: packages/file_selector/file_selector
  flutter:
    sdk: flutter
  mime: ^2.0.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  cross_file_web:
    # When depending on this package from a real application you should use:
    #   cross_file_darwin: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
