name: xdg_directories
description: A Dart package for reading XDG directory configuration information on Linux.
version: 1.0.0-nullsafety.0
homepage: https://github.com/flutter/packages/tree/master/packages/xdg_directories

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0-nullsafety.6
  path: ^1.8.0-nullsafety.3
  process: ^4.0.0-nullsafety.4

dev_dependencies:
  mockito: ^5.0.0-nullsafety.0
  test: ^1.16.0-nullsafety.12
