name: xdg_directories
description: A Dart package for reading XDG directory configuration information on Linux.
version: 0.1.0
homepage: https://github.com/flutter/packages/tree/master/packages/xdg_directories

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  meta: ^1.2.2
  path: ^1.6.4
  process: ^3.0.12

dev_dependencies:
  test: ^1.15.3
  mockito: ^4.1.1
