name: xdg_directories
description: A Dart package for reading XDG directory configuration information on Linux.
version: 0.2.0
homepage: https://github.com/flutter/packages/tree/master/packages/xdg_directories

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0
  path: ^1.8.0
  process: ^4.0.0

dev_dependencies:
  test: ^1.16.0
