name: camera_web_integration_tests
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  camera_platform_interface: ^2.1.0
  camera_web:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  cross_file: ^0.3.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: 0.3.0
