name: pointer_interceptor
description: A widget to prevent clicks from being swallowed by underlying HtmlElementViews on the web.
repository: https://github.com/flutter/packages/tree/main/packages/pointer_interceptor/pointer_interceptor
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+pointer_interceptor%22
version: 0.10.1+2

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: pointer_interceptor_web
      ios:
        default_package: pointer_interceptor_ios

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  pointer_interceptor_ios: ^0.10.0
  pointer_interceptor_platform_interface: ^0.10.0
  pointer_interceptor_web: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - web
  - widgets
  - pointer-interceptor
