name: google_sign_in_ios
description: iOS implementation of the google_sign_in plugin.
repository: https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in_ios
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+google_sign_in%22
version: 5.8.0

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: google_sign_in
    platforms:
      ios:
        dartPluginClass: GoogleSignInIOS
        pluginClass: FLTGoogleSignInPlugin
        sharedDarwinSource: true
      macos:
        dartPluginClass: GoogleSignInIOS
        pluginClass: FLTGoogleSignInPlugin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  google_sign_in_platform_interface: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^22.4.2

topics:
  - authentication
  - google-sign-in

# The example deliberately includes limited-use secrets.
false_secrets:
  - /darwin/Tests/GoogleService-Info.plist
  - /darwin/Tests/GoogleSignInTests.m
  - /example/ios/Runner/Info.plist
  - /example/lib/main.dart
  - /example/macos/Runner/Info.plist
