name: image_picker_macos
description: macOS platform implementation of image_picker
repository: https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker_macos
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22
version: 0.2.1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      macos:
        dartPluginClass: ImagePickerMacOS

dependencies:
  file_selector_macos: ^0.9.1+1
  file_selector_platform_interface: ^2.3.0
  flutter:
    sdk: flutter
  image_picker_platform_interface: ^2.8.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito: 5.4.1
