name: rfw
description: Remote Flutter widgets
repository: https://github.com/flutter/packages/tree/master/packages/rfw
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+rfw%22
version: 1.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
