name: cross_file_example
description: Demonstrates how to use cross files.
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  cross_file:
    # When depending on this package from a real application you should use:
    #   cross_file: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    git:
      url: https://github.com/bparrishMines/packages
      ref: new_crossfile
      path: packages/cross_file/cross_file
  file_selector:
    git:
      url: https://github.com/bparrishMines/packages
      ref: new_file_selector
      path: packages/file_selector/file_selector
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mime: ^2.0.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/hello.txt
