name: test_plugin
description: Pigeon test harness for primary plugin languages.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.test_plugin
        pluginClass: TestPlugin
      ios:
        pluginClass: TestPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: TestPlugin
      macos:
        pluginClass: TestPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: TestPluginCApi

dependencies:
  flutter:
    sdk: flutter
  jni: 
    git:
      url: https://github.com/dart-lang/native/
      path: pkgs/jni
      ref: d3c3acb4c67331e5b22010555f7d4f19d4fb5689
  ffi: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
