name: palette_generator
description: Flutter package for generating palette colors from a source image.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/packages/tree/master/packages/palette_generator
version: 0.2.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  path: ^1.6.1

dev_dependencies:
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.2.0 <3.0.0"
