name: palette_generator
description: Flutter package for generating palette colors from a source image.
repository: https://github.com/flutter/packages/tree/main/packages/palette_generator
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+palette_generator%22
version: 0.3.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.15.21"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
