name: palette_generator
description: Flutter package for generating palette colors from a source image.
homepage: https://github.com/flutter/packages/tree/master/packages/palette_generator
version: 0.3.0-nullsafety.0

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.15.21"
