name: cross_file_ios
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

flutter:
  plugin:
    implements: cross_file
    platforms:
      ios:
        pluginClass: CrossFileIOSPlugin
        dartPluginClass: CrossFileIOS
      android:
        package: dev.flutter.packages.cross_file_android
        pluginClass: CrossFileAndroidPlugin
        dartPluginClass: CrossFileAndroid

dependencies:
  flutter:
    sdk: flutter
  cross_file_platform_interface:
    path: ../cross_file_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
