name: cross_file_ios
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

flutter:
  plugin:
    implements: cross_file
    platforms:
      ios:
        pluginClass: CrossFileIOSPlugin
        dartPluginClass: CrossFileIOS

dependencies:
  flutter:
    sdk: flutter
  cross_file_platform_interface:
    path: ../cross_file_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon:
    git:
      url: git@github.com:bparrishMines/packages.git
      ref: pigeon_helper
      path: packages/pigeon
