name: image_colors
description: A simple example of how to use the PaletteGenerator to load the palette from an image file.

version: 0.1.0

dependencies:
  flutter:
    sdk: flutter
  palette_generator:
    path: ../..
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/landscape.png


