name: web_benchmarks
description: A benchmark harness for performance-testing Flutter apps in Chrome.
version: 0.0.1
homepage: https://github.com/flutter/packages/tree/master/packages/web_benchmarks

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  logging: ">=0.11.4 <1.0.0"
  meta: ">=1.0.0 <2.0.0"
  path: ">=1.7.0 <2.0.0"
  process: ">=3.0.13 <5.0.0"
  shelf: ">=0.7.5 <1.0.0"
  shelf_static: ">=0.2.8 <1.0.0"
  webkit_inspection_protocol: ">=0.7.3 <1.0.0"
