name: google_sign_in_example
description: Example of Google Sign-In plugin.
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in:
    # When depending on this package from a real application you should use:
    #   google_sign_in: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  google_sign_in_web: ^0.12.3
  http: ">=0.13.0 <2.0.0"

dev_dependencies:
  espresso: ^0.4.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
# FOR TESTING AND INITIAL REVIEW ONLY. DO NOT MERGE.
# See https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changing-federated-plugins
dependency_overrides:
  google_sign_in_android: {path: ../../../../packages/google_sign_in/google_sign_in_android}
  google_sign_in_ios: {path: ../../../../packages/google_sign_in/google_sign_in_ios}
  google_sign_in_platform_interface: {path: ../../../../packages/google_sign_in/google_sign_in_platform_interface}
  google_sign_in_web: {path: ../../../../packages/google_sign_in/google_sign_in_web}
