name: google_sign_in_example
description: Example of Google Sign-In plugin.
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in:
    # When depending on this package from a real application you should use:
    #   google_sign_in: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  google_sign_in_platform_interface: ^2.2.0
  google_sign_in_web: ^0.11.0
  http: ^0.13.0

dependency_overrides:
  google_identity_services_web:
    git:
      url: https://github.com/ditman/flutter-packages.git
      ref: gis-web-fix-render-button-api
      path: packages/google_identity_services_web
  google_sign_in_platform_interface:
    path: ../../google_sign_in_platform_interface
  google_sign_in_web:
    path: ../../google_sign_in_web

dev_dependencies:
  espresso: ^0.2.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
