name: platform
description: A pluggable, mockable platform information abstraction for Dart.
repository: https://github.com/flutter/packages/tree/main/packages/platform
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+platform%22
version: 3.1.4

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.16.8

topics:
  - information
  - platform
