name: gauge
description:
  Tools for gauging/measuring some performance metrics.

  Currently there's only one tool to measure iOS CPU/GPU usages for Flutter's CI
  tests.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/packages/tree/master/packages/gauge
version: 0.1.3

executables:
  gauge: gauge

dependencies:
  args: ^1.5.2
  meta: ^1.1.7

dev_dependencies:
  test: ^1.6.8

environment:
  sdk: ">=2.2.2 <3.0.0"
