name: google_adsense
description: A wrapper plugin with convenience APIs allowing easier inserting Google Adsense HTML snippets withing a Flutter UI Web application
repository: https://github.com/flutter/packages/tree/main/packages/google_adsense
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+google_adsense%22
version: 0.1.2

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - monetization
  - ads

screenshots:
  - description: 'Ad displayed in the example app on the desktop browser'
    path: example/images/desktop_screenshot.jpg
  - description: 'Ad displayed in the example app on the mobile browser'
    path: example/images/mobile_screenshot.png