name: standard_message_codec_examples
description: Example code for standard message codec usage
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  standard_message_codec:
    path: ../

dev_dependencies:
  build_runner: ^2.1.10
