name: css_colors
author: Flutter Authors <flutter-dev@googlegroups.com>
description: Defines constants for the CSS Colors
homepage: https://github.com/flutter/css_colors
version: 1.0.2

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=1.0.0 <3.0.0"
  flutter: ">=0.4.4 <2.0.0"
