name: local_auth_windows
description: Windows implementation of the local_auth plugin.
repository: https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth_windows
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+local_auth%22
version: 2.0.1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

flutter:
  plugin:
    implements: local_auth
    platforms:
      windows:
        pluginClass: LocalAuthPlugin
        dartPluginClass: LocalAuthWindows

dependencies:
  flutter:
    sdk: flutter
  local_auth_platform_interface: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^26.1.0

topics:
  - authentication
  - biometrics
  - local-auth
