name: flutter_plugin_tools
description: Productivity and CI utils for flutter/packages
repository: https://github.com/flutter/packages/tree/main/script/tool
version: 1.0.0
publish_to: none

dependencies:
  args: ^2.1.0
  async: ^2.10.0
  collection: ^1.17.0
  colorize: ^3.0.0
  file: ^7.0.1
  git: ^2.0.0
  http: ^1.0.0
  http_multi_server: ^3.0.1
  meta: ^1.10.0
  path: ^1.8.3
  platform: ^3.0.2
  pub_semver: ^2.0.0
  pubspec_parse: ^1.2.2
  quiver: ^3.0.1
  test: ^1.24.0
  uuid: ^4.5.1
  yaml: ^3.1.0
  yaml_edit: ^2.0.2

dev_dependencies:
  build_runner: ^2.2.1
  matcher: ^0.12.15
  mockito: ^5.4.4

environment:
  sdk: ^3.1.0
