name: shared_test_plugin_code
description: Common code for test_plugin and alternate_language_test_plugin
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  build_runner: ^2.1.10
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  # These are normal dependencies rather than dev_dependencies because the
  # package exports the integration test code to be shared by the integration
  # tests for the two plugins.
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  jni: ^0.15.2
  mockito: ^5.4.4
  objective_c: ^9.2.0

dev_dependencies:
  leak_tracker: any
