name: flutter_migrate
description: A tool to migrate legacy flutter projects to modern versions.
version: 0.0.1+4
repository: https://github.com/flutter/packages/tree/main/packages/flutter_migrate
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3Ap%3A%20flutter_migrate
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.3.1
  convert: ^3.0.2
  file:  ">=6.0.0 <8.0.0"
  intl: ">=0.17.0 <0.20.0"
  meta: ^1.8.0
  path: ^1.8.0
  process: ^4.2.4
  vm_service: ^9.3.0
  yaml: ^3.1.1

dev_dependencies:
  collection: ^1.16.0
  file_testing: ^3.0.0
  lints: ^2.0.0
  test: ^1.16.0
