name: file_selector_ios
description: iOS implementation of the file_selector plugin.
repository: https://github.com/flutter/packages/tree/main/packages/file_selector/file_selector_ios
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+file_selector%22
version: 0.5.3+3

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

flutter:
  plugin:
    implements: file_selector
    platforms:
      ios:
        dartPluginClass: FileSelectorIOS
        pluginClass: FileSelectorPlugin

dependencies:
  cross_file_ios:
    path: ../../cross_file/cross_file_ios
  file_selector_platform_interface: ^2.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^25.5.0

topics:
  - files
  - file-selection
  - file-selector
