name: flutter_markdown_example
description: Demonstrates how to use the flutter_markdown package.
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown:
    path: ../
  markdown: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  fonts:
    - family: 'Roboto Mono'
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

  uses-material-design: true
