name: cross_file_web
description: A Flutter plugin that provides a WebView widget on web.
repository: https://github.com/flutter/packages/tree/main/packages/cross_file/cross_file_web
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+cross_file%22
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

flutter:
  plugin:
    implements: cross_file
    platforms:
      web:
        pluginClass: CrossFileWeb
        fileName: cross_file_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ">=0.5.1 <2.0.0"
  cross_file_platform_interface:
    path: ../cross_file_platform_interface

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

topics:
  - file