name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  camera_avfoundation:
    path: ../

  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  quiver: ^3.0.0
  video_player: ^2.1.4

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
