name: file_selector_android
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: file_selector
    platforms:
      android:
        dartPluginClass: FileSelectorAndroid
        package: dev.flutter.packages.file_selector_android
        pluginClass: FileSelectorAndroidPlugin

dependencies:
  file_selector_platform_interface: ^2.5.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  mockito: 5.4.0
  pigeon: ^9.2.4
