name: extension_google_sign_in_example
description: Example of Google Sign-In plugin and googleapis.
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  extension_google_sign_in_as_googleapis_auth:
    # When depending on this package from a real application you should use:
    #   extension_google_sign_in_as_googleapis_auth: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.0
  googleapis: ^10.1.0
  googleapis_auth: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
