name: alternate_language_test_plugin
description: Pigeon test harness for alternate plugin languages.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.alternate_language_test_plugin
        pluginClass: AlternateLanguageTestPlugin
      ios:
        pluginClass: AlternateLanguageTestPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: AlternateLanguageTestPlugin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
