name: fuchsia_ctl
description: >
  A Dart package for paving, serving packages to, and running commands on a
  Fuchsia Device. This package is primarily intended for use in Flutter's
  continuous integration/testing infrastructure.
repository: https://github.com/flutter/packages/tree/master/packages/fuchsia_ctl
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+fuchsia_ctl%22
version: 0.0.24

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  args: ^1.5.2
  file: ^5.0.10
  meta: ^1.1.7
  path: ^1.6.4
  process: ^3.0.12
  retry: ^3.0.0+1
  uuid: ^2.0.2

dev_dependencies:
  mockito: ^4.1.1
  test: ^1.15.5
