name: go_router
description: A declarative router for Flutter based on Navigation 2 supporting
  deep linking, data-driven routes and more
version: 3.0.3
repository: https://github.com/flutter/packages/tree/main/packages/go_router
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+go_router%22

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
