name: go_router
description: A declarative router for Flutter based on Navigation 2 supporting
  deep linking, data-driven routes and more
version: 3.0.1
repository: https://github.com/csells/go_router

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  logging: ^1.0.0
  path_to_regexp: ^0.4.0

dev_dependencies:
  all_lint_rules_community: ^0.0.4
  flutter_test:
    sdk: flutter
