name: maps_example_dart
description: Shared Dart code for the example apps.
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  google_maps_flutter_ios:
    # When depending on this package from a real application you should use:
    #   google_maps_flutter_ios: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../../../
  google_maps_flutter_platform_interface: ^2.2.1

flutter:
  uses-material-design: true
