name: maps_example_dart
description: Shared Dart code for the example apps.
publish_to: none

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.6"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  google_maps_flutter_ios:
    # When depending on this package from a real application you should use:
    #   google_maps_flutter_ios: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../../../
  google_maps_flutter_platform_interface: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  stream_transform: ^2.0.0

flutter:
  uses-material-design: true
