name: webview_flutter_web
description: A Flutter plugin that provides a WebView widget on web.
repository: https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter_web
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 0.2.3+4

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      web:
        pluginClass: WebWebViewPlatform
        fileName: webview_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ">=0.5.1 <2.0.0"
  webview_flutter_platform_interface: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

topics:
  - html
  - webview
  - webview-flutter
# FOR TESTING AND INITIAL REVIEW ONLY. DO NOT MERGE.
# See https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changing-federated-plugins
dependency_overrides:
  webview_flutter_platform_interface: {path: ../../../packages/webview_flutter/webview_flutter_platform_interface}
