name: quick_actions_android
description: An implementation for the Android platform of the Flutter `quick_actions` plugin.
repository: https://github.com/flutter/packages/tree/main/packages/quick_actions/quick_actions_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+in_app_purchase%22
version: 1.0.27

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

flutter:
  plugin:
    implements: quick_actions
    platforms:
      android:
        package: io.flutter.plugins.quickactions
        pluginClass: QuickActionsPlugin
        dartPluginClass: QuickActionsAndroid

dependencies:
  flutter:
    sdk: flutter
  quick_actions_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^26.1.0
  plugin_platform_interface: ^2.1.7

topics:
  - quick-actions
  - os-integration
