name: cross_file_android_example
description: "Demonstrates how to use the cross_file_android plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  cross_file_android:
    path: ../
  mime: ^2.0.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true