name: cross_file_android_example
description: "Demonstrates how to use the cross_file_android plugin."
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  cross_file_android:
    # When depending on this package from a real application you should use:
    #   cross_file_android: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mime: ^2.0.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true