name: imitation_game
description: Testing framework for comparing multiple frameworks' performance.
repository: https://github.com/flutter/packages/tree/main/packages/imitation_game
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+imitation_game%22
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.6.0
  mustache: ^1.1.1
