name: "Creates Batch Release for go_router"

on:
  workflow_dispatch:
  # Uncomment the cron schedule when ready.
  # schedule:
  #   # Run every Monday at 8:00 AM
  #   - cron: "0 8 * * 1"

jobs:
  dispatch_release_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@5fc4efd1a4797ddb68ffd0714a238564e4cc0e6f
        with:
          event-type: batch-release-pr
          client-payload: '{"package": "go_router"}'
