# This workflow applies labels to pull requests based on the
# paths that are modified in the pull request.
#
# Edit `.github/labeler.yml` and `.github/post_merge_labeler.yml`
# to configure labels.
#
# For more information, see: https://github.com/actions/labeler

name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

# Declare default permissions as read only.
permissions: read-all

jobs:
  label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@69da01b8e0929f147b8943611bee75ee4175a49e
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
