name: "Sync Release to Main"

on:
  push:
    branches:
      - 'release-go_router'

jobs:
  create_sync_pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

     - name: Create Pull Request
        uses: peter-evans/create-pull-request@4320041ed380b20e97d388d56a7fb4f9b8c20e79
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "sync release branch to main"
          title: "Sync release branch to main"
          body: "This automated PR syncs the changes from the release branch back to the main branch."
          branch: ${{ github.ref_name }}
          base: main
